export const metadata = {
  title: 'The lakeside manor',
  description: 'Generated by Next.js',
}
import "@/app/_styles/globals.css"
import Logo from "./_components/Logo"
import Navigation from "./_components/Navigation"
import Header from "./_components/Header"
import { ReservationProvider } from "./_components/ReservationContext"
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="relative bg-primary-950 flex flex-col text-primary-100 min-h-screen">
        <Header/>
        <div className="flex-1 px-8 py-12 grid" >
        <main className="max-w-7xl mx-auto w-full">
          <ReservationProvider>{children}</ReservationProvider>
          
          </main>
        </div>
        </body>
    </html>
  )
}
